language: python
python:
  - 2.7
  - 3.4
  - 3.5
install:
  - python setup.py install
  - pip install coverage
script:
  - ls
  - python -m nose -v
notifications:
  email: false
  irc:
    channels: "irc.freenode.org#stellar-py"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
branches:
  only:
    - master
    - dev
    - /^rc-.*$/